-- The database is managed through versioned migrations.
-- For a new project, run `supabase db push` from the repository root.
-- See supabase/migrations/202608060001_customer_ordering.sql for the baseline schema.
