-- Run this in Supabase SQL Editor.

create sequence if not exists public.order_number_seq start 1001;

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  price numeric(10,2),
  available boolean not null default true,
  sugar_option boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint not null default nextval('public.order_number_seq'),
  customer_name text not null check (char_length(customer_name) between 1 and 50),
  customer_notes text check (customer_notes is null or char_length(customer_notes) <= 200),
  status text not null default 'new' check (status in ('new','preparing','completed','cancelled')),
  items jsonb not null,
  total numeric(10,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

insert into public.menu_items (name, price, available, sugar_option, sort_order) values
  ('Hot Americano', null, true, true, 1),
  ('Hot Latte', null, true, true, 2),
  ('Iced Americano', null, true, true, 3),
  ('Iced Latte', null, true, true, 4),
  ('Iced Salted Caramel Latte', null, true, false, 5),
  ('Iced Mont-Blanc', null, true, false, 6),
  ('Iced Espresso Tonic', null, true, false, 7),
  ('Iced Mocha', null, true, false, 8)
on conflict (name) do update set
  sugar_option = excluded.sugar_option,
  sort_order = excluded.sort_order;

alter table public.menu_items enable row level security;
alter table public.orders enable row level security;

-- Public customer menu access
create policy "Anyone can read available menu"
on public.menu_items for select
to anon, authenticated
using (available = true);

-- Customers may create orders
create policy "Anyone can create an order"
on public.orders for insert
to anon, authenticated
with check (status = 'new');

-- Booth dashboard can read and update orders.
-- The PIN in this starter app is a convenience lock, not strong server-side security.
create policy "Dashboard can read orders"
on public.orders for select
to anon, authenticated
using (true);

create policy "Dashboard can update order status"
on public.orders for update
to anon, authenticated
using (true)
with check (status in ('new','preparing','completed','cancelled'));

alter publication supabase_realtime add table public.orders;
